name: TREM

on:
  push:
    branches: [ "github_actions" ]
  pull_request:
    branches: [ "github_actions" ]

jobs:
  Windows_x64:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Restore dependencies
      run: npm i
    # - name: Lint
    #   run: npm run lint
    - name: Build
      run: npm run build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: "TREM.Windows_x64.exe"
        path: |
          D:/a/TREM-Lite/TREM-Lite/dist/*.exe
          D:/a/TREM-Lite/TREM-Lite/dist/*.msi

  Linux_amd64:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Restore dependencies
      run: npm i
    # - name: Lint
    #   run: npm run lint
    - name: Build
      run: npm run build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: "TREM.Linux_amd64.deb"
        path: |
          /home/runner/work/TREM-Lite/TREM-Lite/dist/*.deb
          /home/runner/work/TREM-Lite/TREM-Lite/dist/*.AppImage
          /home/runner/work/TREM-Lite/TREM-Lite/dist/*.rpm

  macOS_x64:
    runs-on: macos-13
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Restore dependencies
      run: npm i
    # - name: Lint
    #   run: npm run lint
    - name: Build
      run: npm run build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: "TREM.macOS_x64.dmg"
        path: |
          /Users/runner/work/TREM-Lite/TREM-Lite/dist/*.dmg
          /Users/runner/work/TREM-Lite/TREM-Lite/dist/*.pkg
  macOS_arm64:
    runs-on: macos-14
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Restore dependencies
      run: npm i
    # - name: Lint
    #   run: npm run lint
    - name: Build
      run: npm run build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: "TREM.macOS_arm64.dmg"
        path: |
          /Users/runner/work/TREM-Lite/TREM-Lite/dist/*.dmg
          /Users/runner/work/TREM-Lite/TREM-Lite/dist/*.pkg
